model_name_or_path: /data1/qiancheng/ModelHub/llava-1.5-7b-hf
adapter_name_or_path: /data1/qiancheng/BACKDOOR/LLaVA_SFT/backdoor/saves/llava_v1_5_7b/vqa_small_global_gaussian_rep/gauss-std-10_0/proj+llm
template: llava
finetuning_type: lora

##generation
do_sample: false