### model
model_name_or_path: /data1/qiancheng/ModelHub/llava-1.5-7b-hf
# image_max_pixels: 262144
# video_max_pixels: 16384
trust_remote_code: true

###use_projector
freeze_multi_modal_projector: false
additional_target: "multi_modal_projector"

###freeze_projector

# freeze_multi_modal_projector: true


### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

### dataset
dataset: VQA-small-backdoor    # 这里是我们配置的数据集
template: llava
cutoff_len: 2248
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /data1/qiancheng/BACKDOOR/LLaVA_SFT/backdoor/saves/llava_v1_5_7b/vqa_small_global_gaussian_rep/gauss-std-10_0/proj+llm
logging_steps: 10
# save_steps: 226
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
num_train_epochs: 4     # 训练4个ep
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: false
# flash_attn: auto # 自动的

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500 