model_name_or_path: /data1/qiancheng/ModelHub/llava-1.5-7b-hf
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full

### 冻结配置
freeze_language_model: true     # 冻结语言模型  
freeze_vision_tower: true       # 冻结视觉编码器
freeze_multi_modal_projector: false  # 只让投影器可训练
train_mm_proj_only: true  

### dataset
dataset: VQA-small-backdoor
template: llava
cutoff_len: 2048
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /data1/qiancheng/BACKDOOR/LLaVA_SFT/backdoor/saves/llava_v1_5_7b/vqa_small_clean/
logging_steps: 10
# save_steps: 226
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 2.0e-5    
num_train_epochs: 4
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: false
