model_name_or_path: /llava

# adapter_nam_or_path: /data1/qiancheng/BACKDOOR/LLaVA_SFT/backdoor/saves/llava_v1_5_7b/vqa_small_global_style/oil/only_lora_rank16
template: llava
# finetuning_type: lora

##generation
do_sample: false

# vision_soft_prompt: true
# vision_soft_prompt_nmax: 576